version: 2.1
orbs:
  cypress: cypress-io/cypress@1.26.0
commands:
  deploy:
    description: "Deployment of webapp"
    parameters:
      hostname:
        type: string
        default: "ssh.staging.openchs.org"
    steps:
      - attach_workspace:
          at: ~/artifacts

      - run:
          name: Install dependencies
          command: |
            sudo apt-get -y -qq update
            sudo apt-get -y -qq install make openssl python3-pip
            sudo pip3 install awscli --upgrade

      - run:
          name: Copy build to server
          command: |
            scp -o StrictHostKeyChecking=no ~/artifacts/openchs-webapp.zip ec2-user@<< parameters.hostname >>:/tmp

      - run:
          name: Deploy app
          command: |
            ssh -o StrictHostKeyChecking=no ec2-user@<< parameters.hostname >> \<< EOF
            sudo rm -rf /opt/openchs-webapp/*
            sudo unzip -qq /tmp/openchs-webapp.zip -d /opt/openchs-webapp
            sudo rm -rf /tmp/openchs-webapp.zip
            EOF

jobs:
  app_test:
    docker:
      - image: circleci/node:10.15.1

    working_directory: ~/openchs-webapp

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run: yarn install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run: yarn test

  app_build:
    docker:
      - image: circleci/node:10.15.1

    working_directory: ~/openchs-webapp

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run: yarn install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run: yarn run build

      - run: cd build; zip -r ../openchs-webapp.zip *

      - run: mkdir -p ~/artifacts

      - run: echo $CIRCLE_BUILD_NUM > ~/artifacts/build_version

      - run: cp ~/openchs-webapp/openchs-webapp.zip ~/artifacts/

      - persist_to_workspace:
          root: ~/artifacts
          paths:
            - build_version
            - openchs-webapp.zip

      - store_artifacts:
          path: ~/artifacts

  STAGING_deploy:
    docker:
      - image: circleci/node:10.15.1
    working_directory: ~/
    steps:
      - deploy:
          hostname: "ssh.staging.openchs.org"

  PRERELEASE_deploy:
    docker:
      - image: circleci/node:10.15.1
    working_directory: ~/
    steps:
      - deploy:
          hostname: "ssh.prerelease.openchs.org"

  PRODUCTION_deploy:
    docker:
      - image: circleci/node:10.15.1
    working_directory: ~/
    steps:
      - deploy:
          hostname: "ssh.server.openchs.org"

workflows:
  version: 2
  test_and_build:
    jobs:
      - app_test
      - app_build:
          requires:
            - app_test
      - STAGING_deploy:
          filters:
            branches:
              only: master
          requires:
            - app_build
      - cypress/run:
          yarn: true
          store_artifacts: true
          requires:
            - STAGING_deploy
          post-steps:
            - store_test_results:
                path: cypress/results
      - PRERELEASE_approve:
          type: approval
          requires:
            - app_build
      - PRERELEASE_deploy:
          requires:
            - PRERELEASE_approve
      - PRODUCTION_approve:
          type: approval
          requires:
            - app_build
      - PRODUCTION_deploy:
          requires:
            - PRODUCTION_approve

notify:
  webhooks:
    - url: https://webhooks.gitter.im/e/0fdffde721194986f2a0
